### ISSUE TITLE
Multilingual Wiki and Picture Choice

### ISSUE THREAD

**Issue by webstar1988** [babydots/babybook#2]
Great App. Thanks.
It would be nice to choose the wiki e.g. .de. com. .es. .. and as well to choose from different photos in case there are multiple in the page.
Thanks and Greetings

**Comment by pserwylo** [comment]
Thanks so much for the feedback (first community member to provide feedback!).

The next release will certainly support choosing images, in a week or so. 

I also love the idea of multilingual wiki's, and will add that to the list of improvements in the future. It should not be particularly onerous to add this feature.

**Comment by pserwylo** [comment]
Okay, so [v0.2.0 has been tagged](https://github.com/babydots/babybook/releases/tag/v0.2.0) and should be picked up by F-Droid in the following week or so. In here, there is a bunch of minor improvements to the UI (feedback welcome) and also allows you to choose any image from a wiki page if you want:

![image](https://user-images.githubusercontent.com/248565/153749182-42f3eec9-b4c2-4ee3-be6e-9030ae2187d1.png)

![image](https://user-images.githubusercontent.com/248565/153749191-a5054210-39b1-4a7a-9080-ea713e78772e.png)

![image](https://user-images.githubusercontent.com/248565/153749198-37acbaeb-0157-4d28-8648-efff966d2df2.png)

When you see the new version on F-Droid, please drop in and let me know what you think!

We'll work on multilingual wiki in the future (is something I want to do, but need to work on image and text attribution first).

**Comment by pserwylo** [comment]
Alright, this can now be closed because [v0.6.0 will support multiple Wikipedia's](https://github.com/babydots/babybook/releases/tag/v0.6.0). Specifically, I've sourced over 70 different wiki's from [this list](https://meta.wikimedia.org/wiki/List_of_Wikipedias) which includes all wiki's with over 100,000 articles on them.

Unfortunately, only English has a "Simple" variant. I was kind of hoping that there would be equivalent simplified versions for other languages so that simple kids books could be created, but alas this doesn't seem to be the case.

Anyway, thanks again for your feedback and let me know what you think once it hits F-Droid over the coming week.

![image](https://user-images.githubusercontent.com/248565/158994640-9f11cb24-d1f4-423d-9cff-84f447f725ef.png)
